// Package mealie provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package mealie

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OAuth2PasswordBearerScopes = "OAuth2PasswordBearer.Scopes"
)

// Defines values for OrderByNullPosition.
const (
	First OrderByNullPosition = "first"
	Last  OrderByNullPosition = "last"
)

// Valid indicates whether the value is a known member of the OrderByNullPosition enum.
func (e OrderByNullPosition) Valid() bool {
	switch e {
	case First:
		return true
	case Last:
		return true
	default:
		return false
	}
}

// Defines values for OrderDirection.
const (
	Asc  OrderDirection = "asc"
	Desc OrderDirection = "desc"
)

// Valid indicates whether the value is a known member of the OrderDirection enum.
func (e OrderDirection) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// Defines values for RegisteredParser.
const (
	Brute  RegisteredParser = "brute"
	Nlp    RegisteredParser = "nlp"
	Openai RegisteredParser = "openai"
)

// Valid indicates whether the value is a known member of the RegisteredParser enum.
func (e RegisteredParser) Valid() bool {
	switch e {
	case Brute:
		return true
	case Nlp:
		return true
	case Openai:
		return true
	default:
		return false
	}
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// IngredientConfidence defines model for IngredientConfidence.
type IngredientConfidence struct {
	Average  *float32 `json:"average,omitempty"`
	Comment  *float32 `json:"comment,omitempty"`
	Food     *float32 `json:"food,omitempty"`
	Name     *float32 `json:"name,omitempty"`
	Quantity *float32 `json:"quantity,omitempty"`
	Unit     *float32 `json:"unit,omitempty"`
}

// IngredientFoodInput defines model for IngredientFood-Input.
type IngredientFoodInput struct {
	Aliases                      *[]IngredientFoodAlias    `json:"aliases,omitempty"`
	CreatedAt                    *time.Time                `json:"createdAt,omitempty"`
	Description                  *string                   `json:"description,omitempty"`
	Extras                       *map[string]interface{}   `json:"extras,omitempty"`
	HouseholdsWithIngredientFood *[]string                 `json:"householdsWithIngredientFood,omitempty"`
	Id                           string                    `json:"id"`
	Label                        *MultiPurposeLabelSummary `json:"label,omitempty"`
	LabelId                      *string                   `json:"labelId,omitempty"`
	Name                         string                    `json:"name"`
	PluralName                   *string                   `json:"pluralName,omitempty"`
	UpdateAt                     *time.Time                `json:"update_at,omitempty"`
}

// IngredientFoodOutput defines model for IngredientFood-Output.
type IngredientFoodOutput struct {
	Aliases                      *[]IngredientFoodAlias    `json:"aliases,omitempty"`
	CreatedAt                    *time.Time                `json:"createdAt,omitempty"`
	Description                  *string                   `json:"description,omitempty"`
	Extras                       *map[string]interface{}   `json:"extras,omitempty"`
	HouseholdsWithIngredientFood *[]string                 `json:"householdsWithIngredientFood,omitempty"`
	Id                           string                    `json:"id"`
	Label                        *MultiPurposeLabelSummary `json:"label,omitempty"`
	LabelId                      *string                   `json:"labelId,omitempty"`
	Name                         string                    `json:"name"`
	PluralName                   *string                   `json:"pluralName,omitempty"`
	UpdatedAt                    *time.Time                `json:"updatedAt,omitempty"`
}

// IngredientFoodAlias defines model for IngredientFoodAlias.
type IngredientFoodAlias struct {
	Name string `json:"name"`
}

// IngredientReferences A list of ingredient references.
type IngredientReferences struct {
	ReferenceId *string `json:"referenceId,omitempty"`
}

// IngredientUnitInput defines model for IngredientUnit-Input.
type IngredientUnitInput struct {
	Abbreviation       *string                 `json:"abbreviation,omitempty"`
	Aliases            *[]IngredientUnitAlias  `json:"aliases,omitempty"`
	CreatedAt          *time.Time              `json:"createdAt,omitempty"`
	Description        *string                 `json:"description,omitempty"`
	Extras             *map[string]interface{} `json:"extras,omitempty"`
	Fraction           *bool                   `json:"fraction,omitempty"`
	Id                 string                  `json:"id"`
	Name               string                  `json:"name"`
	PluralAbbreviation *string                 `json:"pluralAbbreviation,omitempty"`
	PluralName         *string                 `json:"pluralName,omitempty"`
	StandardQuantity   *float32                `json:"standardQuantity,omitempty"`
	StandardUnit       *string                 `json:"standardUnit,omitempty"`
	UpdateAt           *time.Time              `json:"update_at,omitempty"`
	UseAbbreviation    *bool                   `json:"useAbbreviation,omitempty"`
}

// IngredientUnitOutput defines model for IngredientUnit-Output.
type IngredientUnitOutput struct {
	Abbreviation       *string                 `json:"abbreviation,omitempty"`
	Aliases            *[]IngredientUnitAlias  `json:"aliases,omitempty"`
	CreatedAt          *time.Time              `json:"createdAt,omitempty"`
	Description        *string                 `json:"description,omitempty"`
	Extras             *map[string]interface{} `json:"extras,omitempty"`
	Fraction           *bool                   `json:"fraction,omitempty"`
	Id                 string                  `json:"id"`
	Name               string                  `json:"name"`
	PluralAbbreviation *string                 `json:"pluralAbbreviation,omitempty"`
	PluralName         *string                 `json:"pluralName,omitempty"`
	StandardQuantity   *float32                `json:"standardQuantity,omitempty"`
	StandardUnit       *string                 `json:"standardUnit,omitempty"`
	UpdatedAt          *time.Time              `json:"updatedAt,omitempty"`
	UseAbbreviation    *bool                   `json:"useAbbreviation,omitempty"`
}

// IngredientUnitAlias defines model for IngredientUnitAlias.
type IngredientUnitAlias struct {
	Name string `json:"name"`
}

// IngredientsRequest defines model for IngredientsRequest.
type IngredientsRequest struct {
	Ingredients []string          `json:"ingredients"`
	Parser      *RegisteredParser `json:"parser,omitempty"`
}

// MultiPurposeLabelSummary defines model for MultiPurposeLabelSummary.
type MultiPurposeLabelSummary struct {
	Color   *string `json:"color,omitempty"`
	GroupId string  `json:"groupId"`
	Id      string  `json:"id"`
	Name    string  `json:"name"`
}

// Nutrition defines model for Nutrition.
type Nutrition struct {
	Calories              *string `json:"calories,omitempty"`
	CarbohydrateContent   *string `json:"carbohydrateContent,omitempty"`
	CholesterolContent    *string `json:"cholesterolContent,omitempty"`
	FatContent            *string `json:"fatContent,omitempty"`
	FiberContent          *string `json:"fiberContent,omitempty"`
	ProteinContent        *string `json:"proteinContent,omitempty"`
	SaturatedFatContent   *string `json:"saturatedFatContent,omitempty"`
	SodiumContent         *string `json:"sodiumContent,omitempty"`
	SugarContent          *string `json:"sugarContent,omitempty"`
	TransFatContent       *string `json:"transFatContent,omitempty"`
	UnsaturatedFatContent *string `json:"unsaturatedFatContent,omitempty"`
}

// OrderByNullPosition defines model for OrderByNullPosition.
type OrderByNullPosition string

// OrderDirection defines model for OrderDirection.
type OrderDirection string

// PaginationBaseRecipeSummary defines model for PaginationBase_RecipeSummary_.
type PaginationBaseRecipeSummary struct {
	Items      []RecipeSummary `json:"items"`
	Next       *string         `json:"next,omitempty"`
	Page       *int            `json:"page,omitempty"`
	PerPage    *int            `json:"per_page,omitempty"`
	Previous   *string         `json:"previous,omitempty"`
	Total      *int            `json:"total,omitempty"`
	TotalPages *int            `json:"total_pages,omitempty"`
}

// ParsedIngredient defines model for ParsedIngredient.
type ParsedIngredient struct {
	Confidence *IngredientConfidence  `json:"confidence,omitempty"`
	Ingredient RecipeIngredientOutput `json:"ingredient"`
	Input      *string                `json:"input,omitempty"`
}

// RecipeInput defines model for Recipe-Input.
type RecipeInput struct {
	Assets              *[]RecipeAsset           `json:"assets,omitempty"`
	Comments            *[]RecipeCommentOutInput `json:"comments,omitempty"`
	CookTime            *string                  `json:"cookTime,omitempty"`
	CreatedAt           *time.Time               `json:"createdAt,omitempty"`
	DateAdded           *openapi_types.Date      `json:"dateAdded,omitempty"`
	DateUpdated         *time.Time               `json:"dateUpdated,omitempty"`
	Description         *string                  `json:"description,omitempty"`
	Extras              *map[string]interface{}  `json:"extras,omitempty"`
	GroupId             *string                  `json:"groupId,omitempty"`
	HouseholdId         *string                  `json:"householdId,omitempty"`
	Id                  *string                  `json:"id,omitempty"`
	Image               interface{}              `json:"image,omitempty"`
	LastMade            *time.Time               `json:"lastMade,omitempty"`
	Name                *string                  `json:"name,omitempty"`
	Notes               *[]RecipeNote            `json:"notes,omitempty"`
	Nutrition           *Nutrition               `json:"nutrition,omitempty"`
	OrgURL              *string                  `json:"orgURL,omitempty"`
	PerformTime         *string                  `json:"performTime,omitempty"`
	PrepTime            *string                  `json:"prepTime,omitempty"`
	Rating              *float32                 `json:"rating,omitempty"`
	RecipeCategory      *[]RecipeCategory        `json:"recipeCategory,omitempty"`
	RecipeIngredient    *[]RecipeIngredientInput `json:"recipeIngredient,omitempty"`
	RecipeInstructions  *[]RecipeStep            `json:"recipeInstructions,omitempty"`
	RecipeServings      *float32                 `json:"recipeServings,omitempty"`
	RecipeYield         *string                  `json:"recipeYield,omitempty"`
	RecipeYieldQuantity *float32                 `json:"recipeYieldQuantity,omitempty"`
	Settings            *RecipeSettings          `json:"settings,omitempty"`
	Slug                *string                  `json:"slug,omitempty"`
	Tags                *[]RecipeTag             `json:"tags,omitempty"`
	Tools               *[]RecipeTool            `json:"tools,omitempty"`
	TotalTime           *string                  `json:"totalTime,omitempty"`
	UpdateAt            *time.Time               `json:"update_at,omitempty"`
	UserId              *string                  `json:"userId,omitempty"`
}

// RecipeOutput defines model for Recipe-Output.
type RecipeOutput struct {
	Assets              *[]RecipeAsset            `json:"assets,omitempty"`
	Comments            *[]RecipeCommentOutOutput `json:"comments,omitempty"`
	CookTime            *string                   `json:"cookTime,omitempty"`
	CreatedAt           *time.Time                `json:"createdAt,omitempty"`
	DateAdded           *openapi_types.Date       `json:"dateAdded,omitempty"`
	DateUpdated         *time.Time                `json:"dateUpdated,omitempty"`
	Description         *string                   `json:"description,omitempty"`
	Extras              *map[string]interface{}   `json:"extras,omitempty"`
	GroupId             *string                   `json:"groupId,omitempty"`
	HouseholdId         *string                   `json:"householdId,omitempty"`
	Id                  *string                   `json:"id,omitempty"`
	Image               interface{}               `json:"image,omitempty"`
	LastMade            *time.Time                `json:"lastMade,omitempty"`
	Name                *string                   `json:"name,omitempty"`
	Notes               *[]RecipeNote             `json:"notes,omitempty"`
	Nutrition           *Nutrition                `json:"nutrition,omitempty"`
	OrgURL              *string                   `json:"orgURL,omitempty"`
	PerformTime         *string                   `json:"performTime,omitempty"`
	PrepTime            *string                   `json:"prepTime,omitempty"`
	Rating              *float32                  `json:"rating,omitempty"`
	RecipeCategory      *[]RecipeCategory         `json:"recipeCategory,omitempty"`
	RecipeIngredient    *[]RecipeIngredientOutput `json:"recipeIngredient,omitempty"`
	RecipeInstructions  *[]RecipeStep             `json:"recipeInstructions,omitempty"`
	RecipeServings      *float32                  `json:"recipeServings,omitempty"`
	RecipeYield         *string                   `json:"recipeYield,omitempty"`
	RecipeYieldQuantity *float32                  `json:"recipeYieldQuantity,omitempty"`
	Settings            *RecipeSettings           `json:"settings,omitempty"`
	Slug                *string                   `json:"slug,omitempty"`
	Tags                *[]RecipeTag              `json:"tags,omitempty"`
	Tools               *[]RecipeTool             `json:"tools,omitempty"`
	TotalTime           *string                   `json:"totalTime,omitempty"`
	UpdatedAt           *time.Time                `json:"updatedAt,omitempty"`
	UserId              *string                   `json:"userId,omitempty"`
}

// RecipeAsset defines model for RecipeAsset.
type RecipeAsset struct {
	FileName *string `json:"fileName,omitempty"`
	Icon     string  `json:"icon"`
	Name     string  `json:"name"`
}

// RecipeCategory defines model for RecipeCategory.
type RecipeCategory struct {
	GroupId *string `json:"groupId,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
}

// RecipeCommentOutInput defines model for RecipeCommentOut-Input.
type RecipeCommentOutInput struct {
	CreatedAt time.Time                                `json:"createdAt"`
	Id        string                                   `json:"id"`
	RecipeId  string                                   `json:"recipeId"`
	Text      string                                   `json:"text"`
	UpdateAt  time.Time                                `json:"update_at"`
	User      MealieSchemaRecipeRecipeCommentsUserBase `json:"user"`
	UserId    string                                   `json:"userId"`
}

// RecipeCommentOutOutput defines model for RecipeCommentOut-Output.
type RecipeCommentOutOutput struct {
	CreatedAt time.Time      `json:"createdAt"`
	Id        string         `json:"id"`
	RecipeId  string         `json:"recipeId"`
	Text      string         `json:"text"`
	UpdatedAt time.Time      `json:"updatedAt"`
	User      UserBaseOutput `json:"user"`
	UserId    string         `json:"userId"`
}

// RecipeIngredientInput defines model for RecipeIngredient-Input.
type RecipeIngredientInput struct {
	Display          *string              `json:"display,omitempty"`
	Food             *IngredientFoodInput `json:"food,omitempty"`
	Note             *string              `json:"note,omitempty"`
	OriginalText     *string              `json:"originalText,omitempty"`
	Quantity         *float32             `json:"quantity,omitempty"`
	ReferenceId      *openapi_types.UUID  `json:"referenceId,omitempty"`
	ReferencedRecipe *RecipeInput         `json:"referencedRecipe,omitempty"`
	Title            *string              `json:"title,omitempty"`
	Unit             *IngredientUnitInput `json:"unit,omitempty"`
}

// RecipeIngredientOutput defines model for RecipeIngredient-Output.
type RecipeIngredientOutput struct {
	Display          *string               `json:"display,omitempty"`
	Food             *IngredientFoodOutput `json:"food,omitempty"`
	Note             *string               `json:"note,omitempty"`
	OriginalText     *string               `json:"originalText,omitempty"`
	Quantity         *float32              `json:"quantity,omitempty"`
	ReferenceId      *openapi_types.UUID   `json:"referenceId,omitempty"`
	ReferencedRecipe *RecipeOutput         `json:"referencedRecipe,omitempty"`
	Title            *string               `json:"title,omitempty"`
	Unit             *IngredientUnitOutput `json:"unit,omitempty"`
}

// RecipeNote defines model for RecipeNote.
type RecipeNote struct {
	Text  string `json:"text"`
	Title string `json:"title"`
}

// RecipeSettings defines model for RecipeSettings.
type RecipeSettings struct {
	DisableComments *bool `json:"disableComments,omitempty"`
	LandscapeView   *bool `json:"landscapeView,omitempty"`
	Locked          *bool `json:"locked,omitempty"`
	Public          *bool `json:"public,omitempty"`
	ShowAssets      *bool `json:"showAssets,omitempty"`
	ShowNutrition   *bool `json:"showNutrition,omitempty"`
}

// RecipeStep defines model for RecipeStep.
type RecipeStep struct {
	Id                   *openapi_types.UUID     `json:"id,omitempty"`
	IngredientReferences *[]IngredientReferences `json:"ingredientReferences,omitempty"`
	Summary              *string                 `json:"summary,omitempty"`
	Text                 string                  `json:"text"`
	Title                *string                 `json:"title,omitempty"`
}

// RecipeSummary defines model for RecipeSummary.
type RecipeSummary struct {
	CookTime            *string             `json:"cookTime,omitempty"`
	CreatedAt           *time.Time          `json:"createdAt,omitempty"`
	DateAdded           *openapi_types.Date `json:"dateAdded,omitempty"`
	DateUpdated         *time.Time          `json:"dateUpdated,omitempty"`
	Description         *string             `json:"description,omitempty"`
	GroupId             *string             `json:"groupId,omitempty"`
	HouseholdId         *string             `json:"householdId,omitempty"`
	Id                  *string             `json:"id,omitempty"`
	Image               interface{}         `json:"image,omitempty"`
	LastMade            *time.Time          `json:"lastMade,omitempty"`
	Name                *string             `json:"name,omitempty"`
	OrgURL              *string             `json:"orgURL,omitempty"`
	PerformTime         *string             `json:"performTime,omitempty"`
	PrepTime            *string             `json:"prepTime,omitempty"`
	Rating              *float32            `json:"rating,omitempty"`
	RecipeCategory      *[]RecipeCategory   `json:"recipeCategory,omitempty"`
	RecipeServings      *float32            `json:"recipeServings,omitempty"`
	RecipeYield         *string             `json:"recipeYield,omitempty"`
	RecipeYieldQuantity *float32            `json:"recipeYieldQuantity,omitempty"`
	Slug                *string             `json:"slug,omitempty"`
	Tags                *[]RecipeTag        `json:"tags,omitempty"`
	Tools               *[]RecipeTool       `json:"tools,omitempty"`
	TotalTime           *string             `json:"totalTime,omitempty"`
	UpdatedAt           *time.Time          `json:"updatedAt,omitempty"`
	UserId              *string             `json:"userId,omitempty"`
}

// RecipeTag defines model for RecipeTag.
type RecipeTag struct {
	GroupId *string `json:"groupId,omitempty"`
	Id      *string `json:"id,omitempty"`
	Name    string  `json:"name"`
	Slug    string  `json:"slug"`
}

// RecipeTool defines model for RecipeTool.
type RecipeTool struct {
	GroupId            *string   `json:"groupId,omitempty"`
	HouseholdsWithTool *[]string `json:"householdsWithTool,omitempty"`
	Id                 string    `json:"id"`
	Name               string    `json:"name"`
	Slug               string    `json:"slug"`
}

// RegisteredParser defines model for RegisteredParser.
type RegisteredParser string

// ScrapeRecipeData defines model for ScrapeRecipeData.
type ScrapeRecipeData struct {
	Data              string  `json:"data"`
	IncludeCategories *bool   `json:"includeCategories,omitempty"`
	IncludeTags       *bool   `json:"includeTags,omitempty"`
	Url               *string `json:"url,omitempty"`
}

// UserBaseOutput defines model for UserBase-Output.
type UserBaseOutput struct {
	Admin    bool    `json:"admin"`
	FullName *string `json:"fullName,omitempty"`
	Id       string  `json:"id"`
	Username *string `json:"username,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// MealieSchemaRecipeRecipeCommentsUserBase defines model for mealie__schema__recipe__recipe_comments__UserBase.
type MealieSchemaRecipeRecipeCommentsUserBase struct {
	Admin    bool    `json:"admin"`
	FullName *string `json:"fullName,omitempty"`
	Id       string  `json:"id"`
	Username *string `json:"username,omitempty"`
}

// ParseIngredientsApiParserIngredientsPostParams defines parameters for ParseIngredientsApiParserIngredientsPost.
type ParseIngredientsApiParserIngredientsPostParams struct {
	AcceptLanguage *string `json:"accept-language,omitempty"`
}

// GetAllApiRecipesGetParams defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams struct {
	Categories           *[]GetAllApiRecipesGetParams_Categories_Item `form:"categories,omitempty" json:"categories,omitempty"`
	Tags                 *[]GetAllApiRecipesGetParams_Tags_Item       `form:"tags,omitempty" json:"tags,omitempty"`
	Tools                *[]GetAllApiRecipesGetParams_Tools_Item      `form:"tools,omitempty" json:"tools,omitempty"`
	Foods                *[]GetAllApiRecipesGetParams_Foods_Item      `form:"foods,omitempty" json:"foods,omitempty"`
	Households           *[]GetAllApiRecipesGetParams_Households_Item `form:"households,omitempty" json:"households,omitempty"`
	OrderBy              *string                                      `form:"orderBy,omitempty" json:"orderBy,omitempty"`
	OrderByNullPosition  *OrderByNullPosition                         `form:"orderByNullPosition,omitempty" json:"orderByNullPosition,omitempty"`
	OrderDirection       *OrderDirection                              `form:"orderDirection,omitempty" json:"orderDirection,omitempty"`
	QueryFilter          *string                                      `form:"queryFilter,omitempty" json:"queryFilter,omitempty"`
	PaginationSeed       *string                                      `form:"paginationSeed,omitempty" json:"paginationSeed,omitempty"`
	Page                 *int                                         `form:"page,omitempty" json:"page,omitempty"`
	PerPage              *int                                         `form:"perPage,omitempty" json:"perPage,omitempty"`
	Cookbook             *string                                      `form:"cookbook,omitempty" json:"cookbook,omitempty"`
	RequireAllCategories *bool                                        `form:"requireAllCategories,omitempty" json:"requireAllCategories,omitempty"`
	RequireAllTags       *bool                                        `form:"requireAllTags,omitempty" json:"requireAllTags,omitempty"`
	RequireAllTools      *bool                                        `form:"requireAllTools,omitempty" json:"requireAllTools,omitempty"`
	RequireAllFoods      *bool                                        `form:"requireAllFoods,omitempty" json:"requireAllFoods,omitempty"`
	Search               *string                                      `form:"search,omitempty" json:"search,omitempty"`
	AcceptLanguage       *string                                      `json:"accept-language,omitempty"`
}

// GetAllApiRecipesGetParamsCategories0 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsCategories0 = string

// GetAllApiRecipesGetParamsCategories1 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsCategories1 = string

// GetAllApiRecipesGetParams_Categories_Item defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams_Categories_Item struct {
	union json.RawMessage
}

// GetAllApiRecipesGetParamsTags0 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsTags0 = string

// GetAllApiRecipesGetParamsTags1 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsTags1 = string

// GetAllApiRecipesGetParams_Tags_Item defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams_Tags_Item struct {
	union json.RawMessage
}

// GetAllApiRecipesGetParamsTools0 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsTools0 = string

// GetAllApiRecipesGetParamsTools1 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsTools1 = string

// GetAllApiRecipesGetParams_Tools_Item defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams_Tools_Item struct {
	union json.RawMessage
}

// GetAllApiRecipesGetParamsFoods0 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsFoods0 = string

// GetAllApiRecipesGetParamsFoods1 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsFoods1 = string

// GetAllApiRecipesGetParams_Foods_Item defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams_Foods_Item struct {
	union json.RawMessage
}

// GetAllApiRecipesGetParamsHouseholds0 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsHouseholds0 = string

// GetAllApiRecipesGetParamsHouseholds1 defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParamsHouseholds1 = string

// GetAllApiRecipesGetParams_Households_Item defines parameters for GetAllApiRecipesGet.
type GetAllApiRecipesGetParams_Households_Item struct {
	union json.RawMessage
}

// CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams defines parameters for CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost.
type CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams struct {
	AcceptLanguage *string `json:"accept-language,omitempty"`
}

// PatchOneApiRecipesSlugPatchParams defines parameters for PatchOneApiRecipesSlugPatch.
type PatchOneApiRecipesSlugPatchParams struct {
	AcceptLanguage *string `json:"accept-language,omitempty"`
}

// ParseIngredientsApiParserIngredientsPostJSONRequestBody defines body for ParseIngredientsApiParserIngredientsPost for application/json ContentType.
type ParseIngredientsApiParserIngredientsPostJSONRequestBody = IngredientsRequest

// CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody defines body for CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost for application/json ContentType.
type CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody = ScrapeRecipeData

// PatchOneApiRecipesSlugPatchJSONRequestBody defines body for PatchOneApiRecipesSlugPatch for application/json ContentType.
type PatchOneApiRecipesSlugPatchJSONRequestBody = RecipeInput

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ParseIngredientsApiParserIngredientsPostWithBody request with any body
	ParseIngredientsApiParserIngredientsPostWithBody(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ParseIngredientsApiParserIngredientsPost(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, body ParseIngredientsApiParserIngredientsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAllApiRecipesGet request
	GetAllApiRecipesGet(ctx context.Context, params *GetAllApiRecipesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBody request with any body
	CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBody(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, body CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchOneApiRecipesSlugPatchWithBody request with any body
	PatchOneApiRecipesSlugPatchWithBody(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchOneApiRecipesSlugPatch(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, body PatchOneApiRecipesSlugPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ParseIngredientsApiParserIngredientsPostWithBody(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseIngredientsApiParserIngredientsPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ParseIngredientsApiParserIngredientsPost(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, body ParseIngredientsApiParserIngredientsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewParseIngredientsApiParserIngredientsPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAllApiRecipesGet(ctx context.Context, params *GetAllApiRecipesGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAllApiRecipesGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBody(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, body CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchOneApiRecipesSlugPatchWithBody(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchOneApiRecipesSlugPatchRequestWithBody(c.Server, slug, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchOneApiRecipesSlugPatch(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, body PatchOneApiRecipesSlugPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchOneApiRecipesSlugPatchRequest(c.Server, slug, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewParseIngredientsApiParserIngredientsPostRequest calls the generic ParseIngredientsApiParserIngredientsPost builder with application/json body
func NewParseIngredientsApiParserIngredientsPostRequest(server string, params *ParseIngredientsApiParserIngredientsPostParams, body ParseIngredientsApiParserIngredientsPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewParseIngredientsApiParserIngredientsPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewParseIngredientsApiParserIngredientsPostRequestWithBody generates requests for ParseIngredientsApiParserIngredientsPost with any type of body
func NewParseIngredientsApiParserIngredientsPostRequestWithBody(server string, params *ParseIngredientsApiParserIngredientsPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/parser/ingredients")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.AcceptLanguage != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept-language", *params.AcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept-language", headerParam0)
		}

	}

	return req, nil
}

// NewGetAllApiRecipesGetRequest generates requests for GetAllApiRecipesGet
func NewGetAllApiRecipesGetRequest(server string, params *GetAllApiRecipesGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/recipes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Categories != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "categories", *params.Categories, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tags != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tags", *params.Tags, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Tools != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "tools", *params.Tools, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Foods != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "foods", *params.Foods, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Households != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "households", *params.Households, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrderBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "orderBy", *params.OrderBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrderByNullPosition != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "orderByNullPosition", *params.OrderByNullPosition, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrderDirection != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "orderDirection", *params.OrderDirection, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.QueryFilter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "queryFilter", *params.QueryFilter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PaginationSeed != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "paginationSeed", *params.PaginationSeed, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "perPage", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cookbook != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cookbook", *params.Cookbook, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid4"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RequireAllCategories != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "requireAllCategories", *params.RequireAllCategories, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RequireAllTags != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "requireAllTags", *params.RequireAllTags, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RequireAllTools != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "requireAllTools", *params.RequireAllTools, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RequireAllFoods != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "requireAllFoods", *params.RequireAllFoods, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "boolean", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Search != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "search", *params.Search, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.AcceptLanguage != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept-language", *params.AcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept-language", headerParam0)
		}

	}

	return req, nil
}

// NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequest calls the generic CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost builder with application/json body
func NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequest(server string, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, body CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequestWithBody generates requests for CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost with any type of body
func NewCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostRequestWithBody(server string, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/recipes/create/html-or-json")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.AcceptLanguage != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept-language", *params.AcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept-language", headerParam0)
		}

	}

	return req, nil
}

// NewPatchOneApiRecipesSlugPatchRequest calls the generic PatchOneApiRecipesSlugPatch builder with application/json body
func NewPatchOneApiRecipesSlugPatchRequest(server string, slug string, params *PatchOneApiRecipesSlugPatchParams, body PatchOneApiRecipesSlugPatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchOneApiRecipesSlugPatchRequestWithBody(server, slug, params, "application/json", bodyReader)
}

// NewPatchOneApiRecipesSlugPatchRequestWithBody generates requests for PatchOneApiRecipesSlugPatch with any type of body
func NewPatchOneApiRecipesSlugPatchRequestWithBody(server string, slug string, params *PatchOneApiRecipesSlugPatchParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "slug", slug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/recipes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.AcceptLanguage != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "accept-language", *params.AcceptLanguage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("accept-language", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ParseIngredientsApiParserIngredientsPostWithBodyWithResponse request with any body
	ParseIngredientsApiParserIngredientsPostWithBodyWithResponse(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseIngredientsApiParserIngredientsPostResponse, error)

	ParseIngredientsApiParserIngredientsPostWithResponse(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, body ParseIngredientsApiParserIngredientsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseIngredientsApiParserIngredientsPostResponse, error)

	// GetAllApiRecipesGetWithResponse request
	GetAllApiRecipesGetWithResponse(ctx context.Context, params *GetAllApiRecipesGetParams, reqEditors ...RequestEditorFn) (*GetAllApiRecipesGetResponse, error)

	// CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBodyWithResponse request with any body
	CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBodyWithResponse(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse, error)

	CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithResponse(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, body CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse, error)

	// PatchOneApiRecipesSlugPatchWithBodyWithResponse request with any body
	PatchOneApiRecipesSlugPatchWithBodyWithResponse(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchOneApiRecipesSlugPatchResponse, error)

	PatchOneApiRecipesSlugPatchWithResponse(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, body PatchOneApiRecipesSlugPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchOneApiRecipesSlugPatchResponse, error)
}

type ParseIngredientsApiParserIngredientsPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]ParsedIngredient
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ParseIngredientsApiParserIngredientsPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ParseIngredientsApiParserIngredientsPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAllApiRecipesGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginationBaseRecipeSummary
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r GetAllApiRecipesGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAllApiRecipesGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *string
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchOneApiRecipesSlugPatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *interface{}
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r PatchOneApiRecipesSlugPatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchOneApiRecipesSlugPatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ParseIngredientsApiParserIngredientsPostWithBodyWithResponse request with arbitrary body returning *ParseIngredientsApiParserIngredientsPostResponse
func (c *ClientWithResponses) ParseIngredientsApiParserIngredientsPostWithBodyWithResponse(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ParseIngredientsApiParserIngredientsPostResponse, error) {
	rsp, err := c.ParseIngredientsApiParserIngredientsPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseIngredientsApiParserIngredientsPostResponse(rsp)
}

func (c *ClientWithResponses) ParseIngredientsApiParserIngredientsPostWithResponse(ctx context.Context, params *ParseIngredientsApiParserIngredientsPostParams, body ParseIngredientsApiParserIngredientsPostJSONRequestBody, reqEditors ...RequestEditorFn) (*ParseIngredientsApiParserIngredientsPostResponse, error) {
	rsp, err := c.ParseIngredientsApiParserIngredientsPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseParseIngredientsApiParserIngredientsPostResponse(rsp)
}

// GetAllApiRecipesGetWithResponse request returning *GetAllApiRecipesGetResponse
func (c *ClientWithResponses) GetAllApiRecipesGetWithResponse(ctx context.Context, params *GetAllApiRecipesGetParams, reqEditors ...RequestEditorFn) (*GetAllApiRecipesGetResponse, error) {
	rsp, err := c.GetAllApiRecipesGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAllApiRecipesGetResponse(rsp)
}

// CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBodyWithResponse request with arbitrary body returning *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse
func (c *ClientWithResponses) CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBodyWithResponse(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse, error) {
	rsp, err := c.CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse(rsp)
}

func (c *ClientWithResponses) CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithResponse(ctx context.Context, params *CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostParams, body CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse, error) {
	rsp, err := c.CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPost(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse(rsp)
}

// PatchOneApiRecipesSlugPatchWithBodyWithResponse request with arbitrary body returning *PatchOneApiRecipesSlugPatchResponse
func (c *ClientWithResponses) PatchOneApiRecipesSlugPatchWithBodyWithResponse(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchOneApiRecipesSlugPatchResponse, error) {
	rsp, err := c.PatchOneApiRecipesSlugPatchWithBody(ctx, slug, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchOneApiRecipesSlugPatchResponse(rsp)
}

func (c *ClientWithResponses) PatchOneApiRecipesSlugPatchWithResponse(ctx context.Context, slug string, params *PatchOneApiRecipesSlugPatchParams, body PatchOneApiRecipesSlugPatchJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchOneApiRecipesSlugPatchResponse, error) {
	rsp, err := c.PatchOneApiRecipesSlugPatch(ctx, slug, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchOneApiRecipesSlugPatchResponse(rsp)
}

// ParseParseIngredientsApiParserIngredientsPostResponse parses an HTTP response from a ParseIngredientsApiParserIngredientsPostWithResponse call
func ParseParseIngredientsApiParserIngredientsPostResponse(rsp *http.Response) (*ParseIngredientsApiParserIngredientsPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ParseIngredientsApiParserIngredientsPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []ParsedIngredient
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseGetAllApiRecipesGetResponse parses an HTTP response from a GetAllApiRecipesGetWithResponse call
func ParseGetAllApiRecipesGetResponse(rsp *http.Response) (*GetAllApiRecipesGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAllApiRecipesGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginationBaseRecipeSummary
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse parses an HTTP response from a CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostWithResponse call
func ParseCreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse(rsp *http.Response) (*CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRecipeFromHtmlOrJsonApiRecipesCreateHtmlOrJsonPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParsePatchOneApiRecipesSlugPatchResponse parses an HTTP response from a PatchOneApiRecipesSlugPatchWithResponse call
func ParsePatchOneApiRecipesSlugPatchResponse(rsp *http.Response) (*PatchOneApiRecipesSlugPatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchOneApiRecipesSlugPatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
